safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 花开花落
host: wangmingli.github.io
desc: 

custom:
    category:
        Java: Java
        Redis: Redis
        Memcache: Mem
        Tools: Tools
    categories:
      - name:  Java
        title: Java

      - name:  Redis
        title: Redis

      - name:  Memcache
        title: Mem

      - name:  Tools
        title: Tools


    scrollingLoadCount: 0                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: wangmingli
        email: mingli_wang@yahoo.com
        disqus: mingli_wang              # Disqus缩略标识
        gcse: 000346898720731947188:mingli_wang     # Google自定义搜索标识ID
        #github: mingli_wang@yahoo.com                 # GitHub账号
        gravatar: 2e3394a7335badbba471f52cf77b8844  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
